server:
  port: 11005

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: jweb-file
  flyway:
    enabled: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    auto: true
  datasource:
    name: jweb-file
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jweb
    username: postgres
    password: 123456
    
#文件存储服务
file:
  storage:
    site: LOCAL
    accessKey: HihdU53bG684lezbwV5Tbp

  